### ISSUE TITLE
Whether the file that holds the pid can be made compatible, for example, if it exists, it will not be created.

### ISSUE THREAD

**Issue by samoyedsun** [jech/polipo#104]
Couldn't create pid file /tmp/polipo.pid: File exists
Couldn't create pid file /tmp/polipo.pid: File exists
Couldn't create pid file /tmp/polipo.pid: File exists

**Comment by jech** [comment]
The whole point of the pidfile is to prevent double execution.

**Comment by ageis** [comment]
Hey @jech, with regards to this ticket (#20 slightly related) here's a suggestion to reconsider some aspects of the design of the [writePid() function](https://github.com/jech/polipo/blob/master/util.c#L577-L606) in util.c?

The main thing I take issue with is the calls to `exit(1)`. You have a point that PID files are useful for preventing parallel execution, but such functionality is typically handled at a wrapped layer of sysvinit, systemd or supervisord! It doesn't help to exit uncleanly if the PID file already exists and the config directive is specified. For instance, why not check if its stale and if that process still exists?
 
Here are open source examples that don't exit on that condition:

https://github.com/defuse/swatd/blob/master/swatd.c#L351-L363
https://github.com/networkupstools/nut/blob/master/common/common.c#L217-L240
https://github.com/NLnetLabs/unbound/blob/master/daemon/unbound.c#L329-L344
