### ISSUE TITLE
Can we set no_proxy url, just like a black list

### ISSUE THREAD

**Issue by CaiJinKen** [jech/polipo#107]
Hi, i`m new in polioi,

In some case like go mod(this will check a lot of website at once), i want to set proxy for golang.org (because of the fuck firewall, i can`t access it directly), but i don`t want to use proxy for some website, whitch is a private ip address. Did the polipo provide some configuration option to support this? And what should i do in this case? 

Thank you very much!

**Comment by jech** [comment]
Sorry, Polipo is no longer being maintained.
