### ISSUE TITLE
failed start stop polipo web cache

### ISSUE THREAD

**Issue by gh4reeb** [jech/polipo#110]
``
**useruser@user:~$** sudo systemctl start polipo
Job for polipo.service failed because the control process exited with error code.
See "systemctl status polipo.service" and "journalctl -xe" for details.
**useruser@user:~$** sudo journalctl -xe
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit polipo.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Aug 13 18:21:32 user systemd[1]: polipo.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit polipo.service has entered the 'failed' state with result 'exit-code'.
Aug 13 18:21:32 user systemd[1]: Failed to start LSB: Start or stop the polipo web cache.
-- Subject: A start job for unit polipo.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit polipo.service has finished with a failure.
-- 
-- The job identifier is 1933 and the job result is failed.```

**Comment by jech** [comment]
Probably yet another bug with systemd.  At any rate, there's not enough information here.
