### ISSUE TITLE
RFE: fetch next time when online

### ISSUE THREAD

**Issue by leggewie** [jech/polipo#31]
One of the things I loved in WWWOFFLE was the ability to surf in offline mode and have it ask if uncached and thus unavailable items should be fetched next time the program was online.  It would be nice to see similar functionality in polipo.

**Comment by leggewie** [comment]
@jech, let's please continue to discuss this RFE.  I am not sure you understood my request here.

**Comment by jech** [comment]
Could we perhaps move the discussion to the mailing list?

**Comment by leggewie** [comment]
On 15.07.2015 06:03, Juliusz Chroboczek wrote:
> Could we perhaps move the discussion to the mailing list?

@jech: I tried to to that and got no response half a year ago.

http://permalink.gmane.org/gmane.comp.web.polipo.user/3342

**Comment by leggewie** [comment]
@jech I will reopen this ticket as new to make sure it's on the radar and we have a chance to properly discuss it.

**Comment by leggewie** [comment]
I've opened #67 now. I'm happy to discuss this on the ML instead if that is your preference.
