### ISSUE TITLE
[util.c:85]: possible array index out of range ?

### ISSUE THREAD

**Issue by dcb314** [jech/polipo#49]
[util.c:85]: (style) Array index 'i' is used before limits check.

Source code is

    while(string[i] != '\0' && i < n) {

Suggest sanity check array index before use.

**Comment by TierraDelFuego** [comment]
Function that is in, strcmp_n,  is not used according to cppcheck

**Comment by dcb314** [comment]
Feel free to delete the code, then.

**Comment by TierraDelFuego** [comment]
What you'll need to do is fork this project and then delete the code then tag your code then send a pull request to the maintainer of this repo

**Comment by dcb314** [comment]
>What you'll need to do ...

I just find problems. Folks more familiar with the code fix them.

**Comment by jech** [comment]
You can also send a patch to the list.

**Comment by jech** [comment]
Fixed in fa1e2fabfcd1bbf9cca218994e1411768be2ec06.  Thanks.
