### ISSUE TITLE
Ignoring all server-side headers?

### ISSUE THREAD

**Issue by wiseoldman95** [jech/polipo#50]
I am trying to setup Polipo to cache everything that it ever serves, and cache it forever. However, Polipo seems to respect server-side headers. Is it possible to force it to ignore them?

**Comment by jech** [comment]
Not a bug -- please use the polipo-users mailing list for questions.

**Comment by wiseoldman95** [comment]
Ok. Sorry about that.
For anyone interested, the mailing list is here:
https://lists.sourceforge.net/lists/listinfo/polipo-users
