### ISSUE TITLE
ability to force caching disregarding UA/server header

### ISSUE THREAD

**Issue by drzraf** [jech/polipo#52]
In some case (broken or misconfigured server, or for testing purposes) it's pretty useful to force caching disregarding HTTP headers. This is clearly off-standard but useful too.
Filtering by mime-type or server-URL pattern would be a great bonus.

An example:
user-agent send a request (with keep-alive)
server replies:
```
Cache-Control: no-cache, no-store, must-revalidate
Etag: <buggy-etag>
Expire: <in the past>
```

Such requests won't be cached by polipo (relaxTransparency = true, mindlesslyCacheVary = true, cacheIsShared = false)

**Comment by jech** [comment]
Not a bug.  Please use the list for feature requests.
