### ISSUE TITLE
get invalid dns reply id 

### ISSUE THREAD

**Issue by kangmj37** [jech/polipo#53]
if dns transaction id value of 0xf123, get signed int type value of 0xfffff123. 

findQuery() function is so often fails.

-----------------------------------------------------------------------------------------------------------

--- dns.old.c	2015-02-02 20:33:34.507287561 +0900
+++ dns.c	2015-02-02 20:30:08.879290658 +0900
@@ -1373,14 +1373,14 @@ stringToLabels(char *buf, int offset, in
 }
 
 #ifdef UNALIGNED_ACCESS
-#define DO_NTOHS(_d, _s) _d = ntohs(*(short*)(_s));
+#define DO_NTOHS(_d, _s) _d = ntohs(*(unsigned short*)(_s));
 #define DO_NTOHL(_d, _s) _d = ntohl(*(unsigned*)(_s))
-#define DO_HTONS(_d, _s) *(short*)(_d) = htons(_s);
+#define DO_HTONS(_d, _s) *(unsigned short*)(_d) = htons(_s);
 #define DO_HTONL(_d, _s) *(unsigned*)(_d) = htonl(_s)
 #else
 #define DO_NTOHS(_d, _s) \
-do { short _dd; \
-memcpy(&(_dd), (_s), sizeof(short)); \
+do { unsigned short _dd; \
+memcpy(&(_dd), (_s), sizeof(unsigned short)); \
     _d = ntohs(_dd); } while(0)

**Comment by jech** [comment]
Fixed in 466b8c8571d05dc11e23b30c91c1974979acdb36.
