### ISSUE TITLE
cant block https tunnels

### ISSUE THREAD

**Issue by rezad1393** [jech/polipo#58]
hi
i am using polipo compiled from latest version and i am trying to block some advertisement and over tracking connection, but whatever i do i don't see any "blocked" message or similar to it in polipo log.
i have put the log level to 0xFF.
this happens for all the https connection that i am trying to block and many of http ones as well.
for example if i add this line 
example.com
 to forbiddenTunnelsFile,and go to that site it doesn't get blocked and i see this message in polipo log.
"tunnel example.com:443 allowed"
am i missing something?

i have tried many formats,for example for google-analytics domain i tried google-analytics.com ssl.google-analytics.com but nothing works and i still get the message that tunnel allowed for this domain that i have supposedly blocked.

**Comment by jech** [comment]
This is not a bug report.  Support requests should go to the polipo-users mailing list.
