### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by pickfire** [jech/polipo#63]
Hi, I think the following in http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/tor.html should be changed to https://check.torproject.org/
```
Go to ipid.shat.net. It should show you an address that you've never heard about.
```
And in http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/tor.html, change the following to https://torproject.org/

**Comment by jech** [comment]
Fixed, thanks.
