### ISSUE TITLE
What is "Server returned weak ETag" ?

### ISSUE THREAD

**Issue by Arnosir** [jech/polipo#88]
Couldn't read from client: Connection reset by peer
Couldn't read from client: Connection reset by peer
Couldn't read from client: Connection reset by peer
Discarded all objects, 2 chunks and 157 atoms left.
Couldn't read from client: Connection reset by peer
Server returned weak ETag -- ignored.
Server returned weak ETag -- ignored.
Server returned weak ETag -- ignored.
Unsupported Cache-Control directive stale-while-revalidate -- ignored.

Why polipo log output error above?

**Comment by jech** [comment]
@Arnosir, please send questions to the mailing list.  The tracker is for bug reports.

> Couldn't read from client: Connection reset by peer

This means that the client closed the connection before it received all data we sent to it.

> Discarded all objects, 2 chunks and 157 atoms left.

That means that after garbage-collecting all memory, Polipo was left with a small amount it couldn't free.

> Server returned weak ETag -- ignored.

This means that the server sent a weak ETag, but Polipo doesn't support weak ETags.  Polipo will not cache the page after it expires.

> Unsupported Cache-Control directive stale-while-revalidate -- ignored.

This means that the server sent a cache control which Polipo doesn't understand.  Polipo will ignore it.
