### ISSUE TITLE
Local, single-user polipo tries to connect to external IP

### ISSUE THREAD

**Issue by glitsj16** [jech/polipo#89]
Hi, I'm using polipo as a single user on a few machines for a while
now, running with default config. The only param uncommented is
'cacheIsShared = false'.

I confess not looking at it's logfile too often, because it does what
it says on the box... One thing I do notice is a bunch of entrees like:

     'Connect to xxx.xxx.xxx.xxx:80 failed: Connection timed out'

The IP always is the external IP from the local machine. None of
the machines runs an internet-faced web server (strictly 127.0.0.1),
so I do get the timed out part of the log entree.

My question is rather, why is polipo trying to connect to the
external IP at all? Considering the persistancy of these log entrees
I must be making a configuration error somewhere, yet I'm not
seeing it. Any pointers on how to tackle this, an explanation as to
why polipo is trying to connect to those external IP's, etc.?

Grtz, glitsj16

**Comment by jech** [comment]
This is being discussed on the mailing list, closing the ticket.
