### ISSUE TITLE
Doubts in httpServerHandlerHeaders API

### ISSUE THREAD

**Issue by JayaprabhuNadarajan** [jech/polipo#97]
Hi,

I started using polipo recently and i have a doubt.
In the file server.c and in API httpServerHandlerHeaders, Only during the failure cases the memory allocated for headers, etag and via are freed. Most of the other cases they are not freed.
Is this intentional ?

Since i don`t know where to raise this question i raised as issue here.
Sorry, if this is not the right forum

Regards,
Jp

**Comment by jech** [comment]
It happens when the object is expired (in `destroyObject`).

Please do not ask questions in the issue tracker.
